
CREATE DATABASE IF NOT EXISTS `gameReview` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `gameReview`;

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE TABLE `gebruikers` (
  `id` int(4) NOT NULL,
  `username` varchar(255) NOT NULL,
  `password` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `gebruikers`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `gebruikers`
  MODIFY `id` int(4) NOT NULL AUTO_INCREMENT;

CREATE TABLE `games` (
  `id` int(4) NOT NULL,
  `title` varchar(255) NOT NULL,
  `summary` varchar(100) NOT NULL,
  `rating` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `games`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `games`
  MODIFY `id` int(4) NOT NULL AUTO_INCREMENT;
  
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
